name: CI CD is Easy

on:
  push:
    branches:
      - abbos
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Kodni repositorydan olish
      - uses: actions/checkout@v3

      # Java o'rnatamiz (Java 17 LTS tavsiya qilinadi)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

       # Maven dependencylarni o'rnatish va build qilish
      - name: Build with Maven
        run: mvn clean install

      # Testlarni ishga tushurish
      - name: Run tests
        run: mvn test

